### ISSUE TITLE
[request] Helm chart for the tool

### ISSUE THREAD

**Issue by eshepelyuk** [Skarlso/crd-bootstrap#22] opened 2024-01-19 07:27 UTC
Could you add to docs the link to Helm chart to install this app if it exists ?

If not, could you plz publish one to be able to install crd-bootstrap declaratively.

**Comment by Skarlso** [comment] 2024-01-19 07:28
Sure! I'd be happy to create a helm chart. :)

**Comment by Skarlso** [comment] 2024-01-22 08:36
Going to test if the release works and that the helmchart is pushed to the right location so not done with this yet... :)

**Comment by eshepelyuk** [comment] 2024-01-22 10:17
Hello

I've noticed the Helm chart is published - grea, thanks.
Could you also add it to the README as an installation method ?

PS: Also - it could be great if you could list the project in [Artifacthub](https://artifacthub.io/docs/topics/repositories/helm-charts/) for better discoverability.

**Comment by Skarlso** [comment] 2024-01-22 10:19
Hang on a sec... I'm just re-writing the thing to actually use it as intended hahaha. It will publish a github page and the charts will be available publicly... I'll ping this when it's done in a few minutes. :)

**Comment by eshepelyuk** [comment] 2024-01-22 10:20
> Hang on a sec... I'm just re-writing the thing to actually use it as intended hahaha. It will publish a github page and the charts will be available publicly... I'll ping this when it's done in a few minutes. :)

Sorry, wdym with "publish github page" ?

**Comment by Skarlso** [comment] 2024-01-22 10:32
That means the charts should be available to be installed as something like `helm install https://skarlso.github.io/crd-bootstrap/` after each release automatically.

**Comment by eshepelyuk** [comment] 2024-01-22 10:33
> That means the charts should be available to be installed as something like `helm install https://skarlso.github.io/crd-bootstrap/` after each release automatically.

But you already has the chart published to OCI registry, no ?
Why do you go to deprecated and not recommended way of having HTTP based Helm repository ?

**Comment by Skarlso** [comment] 2024-01-22 10:35
>But you already has the chart published to OCI registry, no ?

I don't have that. I only publish the images.

**Comment by eshepelyuk** [comment] 2024-01-22 10:37
> > But you already has the chart published to OCI registry, no ?
> 
> I don't have that. I only publish the images.

Ahh, got it, i though I saw `oci:// ` in helm chart publishing in the merged PR.
But anyway, my suggestion is to just publish helm chart together with docker image to the same OCI registry, instead of dealing with deprecated HTTP based repos.

**Comment by Skarlso** [comment] 2024-01-22 10:38
Yah, that wasn't working sadly. Turned out that the action I was using wasn't using that. Bummer.

Okay, let me try to do this the right way then with the OCI registry thing.

**Comment by eshepelyuk** [comment] 2024-01-22 10:41
> Yah, that wasn't working sadly. Turned out that the action I was using wasn't using that. Bummer.
> 
> Okay, let me try to do this the right way then with the OCI registry thing.

Can you give me an error, I can help you on this.

Basically you should to do smth like this

```
helm registry login ghcr.io -u ${{ env.GH_USER }} -p ${{ env.GH_TOKEN }}
helm package --version ${{ env.VERSION }} --app-version ${{ env.VERSION }} .
helm push ${{ github.event.repository.name }}-${{ env.VERSION }}.tgz oci://ghcr.io/Skarlso/helm
```

**Comment by Skarlso** [comment] 2024-01-22 10:45
Hmm, I was planning on using a different action but that lacks the version support for `--app-version` so I'm gonna do the dirty thing with the helm cli that you're writing. :))

`oci://ghcr.io/skarlso/helm` is this right? shouldn't it be `oci://ghcr.io/skarlso/crd-bootstrap/helm`? If I'm planning to publish more than one chart, it could get confusing. Of course, I know it's a helm registry, so I guess it could have multiple charts, I'm just thinking about discoverability?

**Comment by eshepelyuk** [comment] 2024-01-22 10:50
> Hmm, I was planning on using a different action but that lacks the version support for `--app-version` so I'm gonna do the dirty thing with the helm cli that you're writing. :))
> 
> `oci://ghcr.io/skarlso/helm` is this right? shouldn't it be `oci://ghcr.io/skarlso/crd-bootstrap/helm`? If I'm planning to publish more than one chart, it could get confusing. Of course, I know it's a helm registry, so I guess it could have multiple charts, I'm just thinking about discoverability?

the final name will be

`oci://ghcr.io/skarlso/helm/crd-bootstrap-${VERSION}`

**Comment by Skarlso** [comment] 2024-01-22 10:51
Ah okay.

**Comment by Skarlso** [comment] 2024-01-22 10:56
I'll add the artifact hub config once everything is working fine and I have the latest release version and I've updated the README and whatnot. :)

**Comment by eshepelyuk** [comment] 2024-01-22 10:57
> I'll add the artifact hub config once everything is working fine and I have the latest release version and I've updated the README and whatnot. :)

Thanks a lot !

**Comment by Skarlso** [comment] 2024-01-22 10:58
`ghcr.io/skarlso/helm/crd-bootstrap:v0.3.9` Wooot it worked. I thought that the GITHUB token would need some more permissions, but it worked. :D I guess since it can push packages, it's fine to push anything else too.

Nice, I'll wrap this up nicely, and see what I can do about the artifact hub thing.

**Comment by eshepelyuk** [comment] 2024-01-22 11:01
> `ghcr.io/skarlso/helm/crd-bootstrap:v0.3.9` Wooot it worked. I thought that the GITHUB token would need some more permissions, but it worked. :D I guess since it can push packages, it's fine to push anything else too.
> 
> Nice, I'll wrap this up nicely, and see what I can do about the artifact hub thing.
> 
> I need to make it public first, but GitHub has a Unicorn...

I think helm chart is already public, I can see it.

**Comment by Skarlso** [comment] 2024-01-22 11:04
Oh interesting... I'm getting a denied. I guess it's something on my comp then. Thank you for trying!:)

And thanks for the assist! :) Nice work!

**Comment by Skarlso** [comment] 2024-01-22 11:10
Ah I see. Thanks!

**Comment by Skarlso** [comment] 2024-01-22 11:58
Okay it's fixed in `0.3.10`. But I don't really like that I'm generating the template. I eventually will have to write something sensible. :D

**Comment by eshepelyuk** [comment] 2024-01-22 12:01
> Okay it's fixed in `0.3.10`. But I don't really like that I'm generating the template. I eventually will have to write something sensible. :D

+1. helm templates are 1st class citizen, not smth that can be generated, especially for good helm chart one should be able to provide further customization: e.g. resource limits.

**Comment by Skarlso** [comment] 2024-01-22 12:03
Fiiiineeeeeeeee. :DDDD

**Comment by Skarlso** [comment] 2024-01-22 20:35
Okay, I'm almost done with handcrafting this thing. Eventually, I'll deprecate the old manifests under config and the helm chart will be the one used to install this tool.

**Comment by Skarlso** [comment] 2024-01-22 20:44
https://github.com/Skarlso/crd-bootstrap/pull/24

Okay, not much configuration from the values file ATM, like release names and such aren't configurable. But we can add things as needed. WDYT?

**Comment by Skarlso** [comment] 2024-01-22 21:18
Pushed the new version.. Is it working...? I still have auth issues. :D

**Comment by Skarlso** [comment] 2024-01-22 21:22
Np, I tested it, appears to be working 🎉  ( fixed auth issue, my token expired. :D )

**Comment by Skarlso** [comment] 2024-01-22 21:22
Thank you for all the help and testing! :)) 🙇

**Comment by Skarlso** [comment] 2024-01-24 08:07
Closing in favour of #35 to track further progress. Thanks! 🙇

**Closed by Skarlso** 2024-01-24 08:07 UTC
Labels: enhancement
